;(set-frame-font "Bitstream Vera Sans Mono-10.5")
;(set-frame-font "DejaVu Sans Mono-10.5")
(set-frame-font "Meslo LG S-10.5")
;(set-frame-font "Monaco-11")
;(set-frame-font "Lucida Console-10.5")
;(set-frame-font "Inconsolata-11")

(set-fontset-font (frame-parameter nil 'font)
		    'han '("Microsoft YaHei-10.5" . "unicode-bmp")
		    )
